name: Telegram Auto Bot

on:
  schedule:
    # 매시간 0분에 실행 (UTC 기준이므로 한국 시간 -9시간)
    # 아래 예시는 한국 시간 오전 9시(UTC 00:00)에 실행됩니다.
    - cron: '58 6 * * *' 
  workflow_dispatch: # 수동 실행 버튼 활성화

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: 저장소 코드 가져오기
        uses: actions/checkout@v3

      - name: 파이썬 설치
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: 필요한 라이브러리 설치
        run: pip install requests

      - name: 코드 실행
        env:
          # 위에서 설정한 Secret 값을 가져옵니다.
          TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
        run: python TeleBot.py
